# Generated by Django 5.0.2 on 2024-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subgroup',
            field=models.ManyToManyField(blank=True, related_name='users', to='register_login.subgroup'),
        ),
    ]
